---
title: "Klamath Basin Flow Gage EDA"
output: 
  html_document:
    toc_depth: 2
    theme: flatly
    code_folding: hide
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE, 
  message = FALSE,
  comment = "#>", 
  fig.width=8, fig.height=5)
library(googleCloudStorageR)
library(tidyverse)
library(SRJPEdata)
library(lubridate)
library(sf)
library(leaflet)

colors_full <-  c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089", #Royal 2
                  "#899DA4", "#C93312", "#DC863B", # royal 1 (- 3)
                  "#F1BB7B", "#FD6467", "#5B1A18", # Grand Budapest 1 (-4)
                  "#D8B70A", "#02401B", "#A2A475", # Cavalcanti 1
                  "#E6A0C4", "#C6CDF7", "#D8A499", "#7294D4", #Grand Budapest 2
                  "#9986A5", "#EAD3BF", "#AA9486", "#B6854D", "#798E87" # Isle of dogs 2 altered slightly
)
```

## Define Geographic Extent 


## Some potential gages to look at 

### 11509500 - Klamath River at Keno Or
### 11510700 - Klamath River Below John C Boyle Powerplant
### 11516530 - Klamath River Below Iorngate Dam 
### 11520500 - Klamath River Nr Seiad Valley CA
### 11523000 - Klamath River A Orleans 
### 11530500 - Klamath River Near Klamath (Furthest Downstream)
## Pull Gage Data 

## Compare Gage Sources

```{r}
kr_at_keno_or <- dataRetrieval::readNWISdv(11509500, "00060", startDate = "1950-01-01") |> 
  select(date = Date, value =  X_00060_00003) |>  # rename to value
  as_tibble() |> 
  mutate(stream = "klamath river", # add additional columns for stream, gage info, and parameter 
         order = 1,
         gage_agency = "USGS",
         gage_number = "11509500",
         parameter = "flow",
         statistic = "mean", # if query returns instantaneous data then report a min, mean, and max
         latitude = dataRetrieval::readNWISsite("11509500")$dec_lat_va, # directly add lat
         longitude = dataRetrieval::readNWISsite("11509500")$dec_long_va # directly add lon
         )
kr_blw_powerplant <- dataRetrieval::readNWISdv(11510700, "00060", startDate = "1995-01-01") |> 
  select(date = Date, value =  X_00060_00003) |>  # rename to value
  as_tibble() |> 
  mutate(stream = "klamath river", # add additional columns for stream, gage info, and parameter 
         order = 2,
         gage_agency = "USGS",
         gage_number = "11510700",
         parameter = "flow",
         statistic = "mean", # if query returns instantaneous data then report a min, mean, and max
                  latitude = dataRetrieval::readNWISsite("11510700")$dec_lat_va, # directly add lat
         longitude = dataRetrieval::readNWISsite("11510700")$dec_long_va # directly add lon
         ) 
kr_blw_iorngage <- dataRetrieval::readNWISdv(11516530, "00060", startDate = "1950-01-01") |> 
  select(date = Date, value =  X_00060_00003) |>  # rename to value
  as_tibble() |> 
  mutate(stream = "klamath river", # add additional columns for stream, gage info, and parameter 
         order = 3,
         gage_agency = "USGS",
         gage_number = "11516530",
         parameter = "flow",
         statistic = "mean", # if query returns instantaneous data then report a min, mean, and max
         latitude = dataRetrieval::readNWISsite("11516530")$dec_lat_va, # directly add lat
         longitude = dataRetrieval::readNWISsite("11516530")$dec_long_va # directly add lon
         ) 
kr_nr_seiad_valley <- dataRetrieval::readNWISdv(11520500, "00060", startDate = "1950-01-01") |> 
  select(date = Date, value =  X_00060_00003) |>  # rename to value
  as_tibble() |> 
  mutate(stream = "klamath river", # add additional columns for stream, gage info, and parameter 
         order = 4,
         gage_agency = "USGS",
         gage_number = "11520500",
         parameter = "flow",
         statistic = "mean", # if query returns instantaneous data then report a min, mean, and max
         latitude = dataRetrieval::readNWISsite("11520500")$dec_lat_va, # directly add lat
         longitude = dataRetrieval::readNWISsite("11520500")$dec_long_va # directly add lon
         ) 
kr_at_orleans <- dataRetrieval::readNWISdv(11523000, "00060", startDate = "1950-01-01") |> 
  select(date = Date, value =  X_00060_00003) |>  # rename to value
  as_tibble() |> 
  mutate(stream = "klamath river", # add additional columns for stream, gage info, and parameter 
         order = 5,
         gage_agency = "USGS",
         gage_number = "11523000",
         parameter = "flow",
         statistic = "mean", # if query returns instantaneous data then report a min, mean, and max
         latitude = dataRetrieval::readNWISsite("11523000")$dec_lat_va, # directly add lat
         longitude = dataRetrieval::readNWISsite("11523000")$dec_long_va # directly add lon
         ) 
kr_nr_klamath <- dataRetrieval::readNWISdv(11530500, "00060", startDate = "1950-01-01") |> 
  select(date = Date, value =  X_00060_00003) |>  # rename to value
  as_tibble() |> 
  mutate(stream = "klamath river", # add additional columns for stream, gage info, and parameter 
         order = 6,
         gage_agency = "USGS",
         gage_number = "11530500",
         parameter = "flow",
         statistic = "mean", # if query returns instantaneous data then report a min, mean, and max
         latitude = dataRetrieval::readNWISsite("11530500")$dec_lat_va, # directly add lat
         longitude = dataRetrieval::readNWISsite("11530500")$dec_long_va # directly add lon
         )

all_kalamth_usgs_gages <- bind_rows(kr_at_keno_or, kr_blw_powerplant, kr_blw_iorngage, kr_nr_seiad_valley, 
                                    kr_at_orleans, kr_nr_klamath) |> 
  glimpse()
```
## Plot Klamath USGS Gages

```{r}
# Filter to keep only one unique gage per location
unique_gage_data <- all_kalamth_usgs_gages |> 
  distinct(gage_number, latitude, longitude, .keep_all = TRUE)

unique_gage_sf <- unique_gage_data |> 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

leaflet(unique_gage_sf) |> 
  addTiles() |> 
  addCircleMarkers(label = ~gage_number)
```


```{r}
all_kalamth_usgs_gages |> ggplot(aes(x = date, y = value, color = as.character(order))) + 
  geom_line() + 
  scale_color_manual(values = colors_full) +
  facet_wrap(~order) +
  theme_minimal()


all_kalamth_usgs_gages |> 
  ggplot(aes(x = date, y = value, color = gage_number)) + 
  geom_line() + 
  scale_color_manual(values = colors_full) +
  theme_minimal()
```

Exploring NA values

```{r}
date_range_summary <- all_kalamth_usgs_gages |> 
  group_by(gage_number) |> 
  summarize(
    min_date = min(date),  
    max_date = max(date),  
    record_count = n()) |> 
  ungroup()  

```

```{r}
# looking for date gaps
kr_at_keno_or |> 
  ggplot(aes(date, value)) +
  geom_line()

kr_blw_powerplant |> 
  ggplot(aes(date, value)) +
  geom_line()

kr_blw_iorngage |> 
  ggplot(aes(date, value)) +
  geom_line()

kr_nr_seiad_valley |> 
  ggplot(aes(date, value)) +
  geom_line()

kr_at_orleans |> 
  ggplot(aes(date, value)) +
  geom_line()

kr_nr_klamath |> 
  ggplot(aes(date, value)) +
  geom_line()


# date_gaps_per_gage <- all_kalamth_usgs_gages %>%
#   group_by(gage_number) %>%
#   summarize(
#     min_date = min(date, na.rm = TRUE),
#     max_date = max(date, na.rm = TRUE)
#   ) %>%
#   rowwise() %>%
#   mutate(
#     full_date_range = list(seq.Date(from = min_date, to = max_date, by = "day"))
#   ) %>%
#   unnest(full_date_range) %>%
#   rename(date = full_date_range) %>%
#   select(gage_number, date)
# 

#creating a map to show temporal coverage

temp_coverage <- all_kalamth_usgs_gages |> 
  mutate(min_date = min(date),
         max_date = max(date))

```

